### ISSUE TITLE
Running lab up after changed .env or .env.template let CLI crash.

### ISSUE THREAD

**Issue by regnerisch** [labor-digital/lab-cli#4]
When I add or change a value inside the .env/.env.template e.g. `APP_NEW_CUSTOM_VALUE=1` and run `lab up` to load the new environment variable the CLI crashes.

```
Godmorgen, you are using LAB 3.4.1
Found changes on your docker app files! Checking your setup...

A FATAL ERROR OCCURRED!
Sadly I could not recover :(

Error: Hosts file conflict: The domain esp-web-wor.localmachine.space was already registered with another app at: C:\Users\Jonas!
    at C:\Users\J R\AppData\Roaming\npm\node_modules\@labor-digital\lab-cli\lib\Classes\Core\DockerApp\DockerHosts.js:70:31
    at Map.forEach (<anonymous>)
    at DockerHosts.set (C:\Users\J R\AppData\Roaming\npm\node_modules\@labor-digital\lab-cli\lib\Classes\Core\DockerApp\DockerHosts.js:65:23)
    at DockerAppInit.registerDomainInHostsFile (C:\Users\J R\AppData\Roaming\npm\node_modules\@labor-digital\lab-cli\lib\Classes\Core\DockerApp\DockerAppInit.js:206:15)
    at C:\Users\J R\AppData\Roaming\npm\node_modules\@labor-digital\lab-cli\lib\Classes\Core\DockerApp\DockerAppInit.js:83:30
```

**Comment by Neunerlei** [comment]
Hello,

as the error states , the problem is your defined APP_DOMAIN, because it was already registered for another app in your hosts file. Domains, however, have to be unique on your setup, in order for the script to map them to the correct container.

This can occur if you moved your app to another location or copied the app sources to a new location and did not adjust your .env file accordingly. 

You have two possible solutions to this problem:

1. If you moved the app, open your hosts file and remove the broken entry manually
2. If you copied the app, adjust the COMPOSE_PROJECT_NAME and clear out APP_DOMAIN in the .env of your copied app. This will create a new domain.

Does that help?

Cheers!

**Comment by regnerisch** [comment]
I did not move my project. I think this problem is caused by spaces. See this line inside the error-log: `The domain esp-web-wor.localmachine.space was already registered with another app at: C:\Users\Jonas!`

**Comment by Neunerlei** [comment]
Hey, thank you.
Sorry for the delay, I'm currently really busy and would appreciate if you could test on your installation if this line is somehow involved in your issue:

https://github.com/labor-digital/lab-cli/blob/master/src/Classes/Core/DockerApp/DockerHosts.ts#L228

Maybe you could do a console.log(a, before, ip, between, domain, appMarker, appName); in front of line 230 and see if the regex greps the wrong values?

Thank you!

**Comment by Neunerlei** [comment]
Could it be, that you are not using the version 3.4.3, but something like 3.4.1 instead? 
This behavior should be fixed since this commit: https://github.com/labor-digital/lab-cli/commit/0daa5c3390195cd0a9631d43135c2d5b4f5799e0

**Comment by regnerisch** [comment]
Yes... I did not upgrade 🤦
